DROP TABLE IF EXISTS tags;
DROP TABLE IF EXISTS nodes;

CREATE TABLE nodes(
  id BIGINT PRIMARY KEY,
  username text NOT NULL,
  lon DOUBLE PRECISION NOT NULL,
  lat DOUBLE PRECISION NOT NULL
);

CREATE TABLE tags(
  id SERIAL PRIMARY KEY,
  node_id BIGINT NOT NULL REFERENCES nodes(id),
  k text NOT NULL,
  v text NOT NULL
);